clubDeployment:
  gigboardClub:
    env:
      springProfilesActive: prod
    image:
      repository: heyh0/gigboard-club
      tag: '1'
    imagePullPolicy: Always
  replicas: 1
clubService:
  ports:
    - port: 8092
      targetPort: 8092
  type: ClusterIP
eurekaDeployment:
  gigboardEureka:
    env:
      springProfilesActive: prod
    image:
      repository: heyh0/gigboard-eureka
      tag: latest
    imagePullPolicy: Always
  replicas: 1
eurekaService:
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
gatewayDeployment:
  gigboardGateway:
    env:
      springProfilesActive: prod
    image:
      repository: heyh0/gigboard-gateway
      tag: '5'
    imagePullPolicy: Always
  replicas: 1
gatewayService:
  ports:
    - port: 8090
      targetPort: 8090
  type: ClusterIP
kubernetesClusterDomain: cluster.local
placeDeployment:
  gigboardPlace:
    env:
      springProfilesActive: prod
    image:
      repository: heyh0/gigboard-place
      tag: latest
    imagePullPolicy: Always
  replicas: 1
placeService:
  ports:
    - port: 8093
      targetPort: 8093
  type: ClusterIP
recruitDeployment:
  gigboardRecruit:
    env:
      springProfilesActive: prod
    image:
      repository: heyh0/gigboard-recruit
      tag: latest
    imagePullPolicy: Always
  replicas: 1
recruitService:
  ports:
    - port: 8094
      targetPort: 8094
  type: ClusterIP
userDeployment:
  gigboardUser:
    env:
      springProfilesActive: prod
    image:
      repository: heyh0/gigboard-user
      tag: '1'
    imagePullPolicy: Always
  replicas: 1
userService:
  ports:
    - port: 8091
      targetPort: 8091
  type: ClusterIP
