apiVersion: v1
kind: Service
metadata:
  name: club-service
  labels:
  {{- include "gigboard-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.clubService.type }}
  selector:
    app: gigboard-club
  {{- include "gigboard-helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.clubService.ports | toYaml | nindent 2 }}