apiVersion: v1
kind: Service
metadata:
  name: place-service
  labels:
  {{- include "gigboard-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.placeService.type }}
  selector:
    app: gigboard-place
  {{- include "gigboard-helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.placeService.ports | toYaml | nindent 2 }}