apiVersion: v1
kind: Service
metadata:
  name: recruit-service
  labels:
  {{- include "gigboard-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.recruitService.type }}
  selector:
    app: gigboard-recruit
  {{- include "gigboard-helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.recruitService.ports | toYaml | nindent 2 }}